# Часть первая

## Библиотека NumPy

In [23]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([7,3,5,1,8,2,6,9,4])
z = x+y
m = x*y
mm = np.vdot(x,y)
print("x = ",x)
print("y = ",y)
print("z = x + y = ",z)
print("m = x * y = ",m)
print("mm = x dot y = ",mm)

x =  [1 2 3 4 5 6 7 8 9]
y =  [7 3 5 1 8 2 6 9 4]
z = x + y =  [ 8  5  8  5 13  8 13 17 13]
m = x * y =  [ 7  6 15  4 40 12 42 72 36]
mm = x dot y =  234


In [3]:
slice = x[3:5]
print(slice)

slice_with_step = y[1:6:2]
print(slice_with_step)

[4 5]
[3 1 2]


In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("shape arr = ",arr.shape)

print("arr[0] = ",arr[0])

shape arr =  (3, 3)
arr[0] =  [1 2 3]


In [5]:
sarr = arr[0::2]
print(sarr)
qarr = arr[0::2,0::2]
print(qarr)

[[1 2 3]
 [7 8 9]]
[[1 3]
 [7 9]]


In [6]:
rand_array = np.random.rand(2,3)

print(rand_array)


[[0.90886381 0.90801509 0.8923562 ]
 [0.79329864 0.26534654 0.29678912]]


In [7]:
s = np.random.normal()

print(s)

-0.47836572815842227


In [15]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
B = A.transpose()
D = np.linalg.det(A)

print(B)
print(D)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0


In [19]:
V = np.array([1,2,3,4,5])

N = np.linalg.norm(V)

Q = np.linalg.norm(V,np.inf)

print(N)
print(Q)

7.416198487095663
5.0


In [25]:
M = np.array([[2,5],[4,3]])

IM = np.linalg.inv(M)

print(IM)

R = np.matmul(IM,M)

print(R)

[[-0.21428571  0.35714286]
 [ 0.28571429 -0.14285714]]
[[1.00000000e+00 5.55111512e-17]
 [0.00000000e+00 1.00000000e+00]]
