# PB формат

In [1]:
import tensorflow as tf

In [20]:
with tf.Session() as sess:
    with tf.gfile.GFile('../models/mnist.pb', 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        
        sess.graph.as_default()
        tf.import_graph_def(graph_def, name='')
        
        operations = sess.graph.get_operations()
        
        graph = tf.get_default_graph()
        
        for n in operations:
            pass
            
        
        # == previous for
        for n in graph.as_graph_def().node:
            pass
            #print(n)
        
        print(operations[3])
        
        s = graph.get_tensor_by_name(operations[3].name+':0')
           
        print(s.eval())

name: "weights/Assign"
op: "Assign"
input: "weights"
input: "zeros"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "use_locking"
  value {
    b: true
  }
}
attr {
  key: "validate_shape"
  value {
    b: true
  }
}

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
