# Часть первая

## Библиотека NumPy

In [2]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([7,3,5,1,8,2,6,9,4])
z = x+y
print("x = ",x)
print("y = ",y)
print("z = x + y = ",z)

x =  [1 2 3 4 5 6 7 8 9]
y =  [7 3 5 1 8 2 6 9 4]
z = x + y =  [ 8  5  8  5 13  8 13 17 13]


In [3]:
slice = x[3:5]
print(slice)

slice_with_step = y[1:6:2]
print(slice_with_step)

[4 5]
[3 1 2]


In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("shape arr = ",arr.shape)

print("arr[0] = ",arr[0])

shape arr =  (3, 3)
arr[0] =  [1 2 3]


In [5]:
sarr = arr[0::2]
print(sarr)
qarr = arr[0::2,0::2]
print(qarr)

[[1 2 3]
 [7 8 9]]
[[1 3]
 [7 9]]


In [6]:
rand_array = np.random.rand(2,3)

print(rand_array)


[[0.03851175 0.16092634 0.41250559]
 [0.39275939 0.4202518  0.93391548]]


In [9]:
s = np.random.normal()

print(s)

0.3027793016508071
