# TensorFlow



In [2]:
import tensorflow as tf
import numpy as np

x = tf.constant(123.,name="x")
y = tf.constant(234.,name="y")
z = tf.add(x,y,name="z")
    
init = tf.global_variables_initializer()
    
with tf.Session() as sess:
    sess.run(init)
    out = sess.run(z)
    print(out)

357.0


In [3]:
x    = tf.Variable(0.0,name="X")
inc  = x.assign(x+1.0)    

init = tf.global_variables_initializer()
    
with tf.Session() as sess:
    sess.run(init)
    for i in range(10):
        z = sess.run(inc)
        print(z)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [4]:
weight_initializer = tf.variance_scaling_initializer(mode="fan_avg", distribution="uniform", scale=1)
    
X = tf.Variable(weight_initializer([2,3]))
    
init = tf.global_variables_initializer()
    
with tf.Session() as sess:
    sess.run(init)
    out = sess.run(X)
    print(out)

[[-0.61761415  0.9979272   0.72891474]
 [-0.38725466  0.12350023  0.10893297]]


In [5]:
A = tf.placeholder(tf.float32,[None,5],name="A")
B = tf.placeholder(tf.float32,[None,5],name="B")
C = tf.add(A,B,name="C")

with tf.Session() as sess:
    randA = np.random.rand(1,5)
    randB = np.random.rand(1,5)
    out   = sess.run(C, feed_dict={A: randA,B : randB})
    print(randA)
    print(randB)
    print(out)


[[0.42639746 0.26465098 0.77241194 0.66987372 0.53988522]]
[[0.15430506 0.48024252 0.86934438 0.88386248 0.89774834]]
[[0.5807025 0.7448935 1.6417563 1.5537362 1.4376335]]


In [6]:
zeros_tensor = tf.zeros([3, 3])

with tf.Session() as sess:
    print(zeros_tensor.eval())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
x = np.arange(0,  10)
y = np.arange(11, 21)

dx = tf.data.Dataset.from_tensor_slices(x)
dy = tf.data.Dataset.from_tensor_slices(y)

dset     = tf.data.Dataset.zip((dx, dy)).batch(4)
iterator = dset.make_initializable_iterator()

next_element = iterator.get_next()

with tf.Session() as sess:
    sess.run(iterator.initializer)
    for i in range(3):
        val = sess.run(next_element)
        print(val)

(array([0, 1, 2, 3]), array([11, 12, 13, 14]))
(array([4, 5, 6, 7]), array([15, 16, 17, 18]))
(array([8, 9]), array([19, 20]))


In [8]:
y = np.array([1,3,2,0])
    
Y = tf.keras.utils.to_categorical(y,4)

print(Y)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [21]:
STORE_PATH = '../graphs'

GX = tf.placeholder(tf.float32,[3,3],name="GX")
GY = tf.placeholder(tf.float32,[3,3],name="GY")
GZ = tf.multiply(GX,GY,name="GZ")

with tf.Session() as sess:
    rgx = np.random.rand(3,3)
    rgy = np.random.rand(3,3)
    
    out = sess.run(GZ, feed_dict={GX: rgx,GY : rgy})
    
    writer = tf.summary.FileWriter(STORE_PATH, sess.graph)